In [47]:
import pandas as pd
import numpy as np
from datetime import datetime, time
import matplotlib.pyplot as plt
%matplotlib inline
import os
import os.path

In [2]:
#Cleaning up Timestamp issue for some files
#p = pd.read_csv('./MS_Band_Raw/6_logger_data/Day22.csv', skiprows=1)
#p.insert(0, 'PID', 6, allow_duplicates=False)
#p['24'] = p['Time Stamp']  * 24
#p['H'] = int(p['24'])
#p['H-1'] = p['24'] - int(p['24'])
#p['60'] = p['H-1'] * 60
#p['M'] = int(p['60'])
#p['M-1'] = p['60'] - int(p['60'])
#p['S'] = p['M-1'] * 60
#p['Time Stamp'] = datetime.time([p['H'], p['M'], p['S']])
#p['Time Stamp'] = pd.to_datetime(p['Time Stamp'])
#p = p.drop(['Time Stamp', 'Unnamed: 3', 'Unnamed: 4','H', 'Unnamed: 6','Unnamed: 7','M','Unnamed: 9','S'], axis=1)
#p['Time Stamp'] = p['Time Stamp2']
#p = p.drop(['Time Stamp2'], axis=1)

In [65]:
patients = []
plist = os.listdir('./MS_Band_Raw/')

for m in range(1,len(plist)):
    list = os.listdir('./MS_Band_Raw/%d_logger_data' % m)
    if m == 7:
        continue
    print(m, 'Participant has been read')
    for i in range(1, len(list)):
        p = pd.read_csv('./MS_Band_Raw/%d_logger_data/Day%d.csv' % (m,i), skiprows=1)
        p.insert(0, 'PID', m, allow_duplicates=False)
        p.insert(1,'DAY',i, allow_duplicates=False)
        if 8< len(p['Time Stamp'].loc[1]) < 11:
            p['Time Stamp'] = pd.to_datetime(p['Time Stamp'], format='%H:%M:%S %p').dt.time
        elif len(p['Time Stamp'].loc[1]) > 11:
            p['Time Stamp'] = pd.to_datetime(p['Time Stamp'], format='%H:%M:%S.%f').dt.time
        else:
            p['Time Stamp'] = pd.to_datetime(p['Time Stamp']).dt.time
#        p['Time Stamp'] = pd.to_timestamp(p['Time Stamp'])
        patients.append(p)
        print(i, 'Day has been read')

1 Participant has been read
1 Day has been read
2 Day has been read
3 Day has been read
4 Day has been read
5 Day has been read
6 Day has been read
7 Day has been read
8 Day has been read
2 Participant has been read
1 Day has been read
2 Day has been read
3 Day has been read
4 Day has been read
5 Day has been read
6 Day has been read
7 Day has been read
8 Day has been read
9 Day has been read
10 Day has been read
11 Day has been read
12 Day has been read
13 Day has been read
14 Day has been read
15 Day has been read
16 Day has been read
17 Day has been read
18 Day has been read
19 Day has been read
20 Day has been read
21 Day has been read
3 Participant has been read
1 Day has been read
2 Day has been read
3 Day has been read
4 Day has been read
5 Day has been read
6 Day has been read
7 Day has been read
8 Day has been read
9 Day has been read
10 Day has been read
11 Day has been read
12 Day has been read
4 Participant has been read
1 Day has been read
2 Day has been read
3 Day has been read
4 Day has been read
5 Day has been read
6 Day has been read
7 Day has been read
8 Day has been read
9 Day has been read
10 Day has been read
11 Day has been read
12 Day has been read
13 Day has been read
14 Day has been read
15 Day has been read
5 Participant has been read
1 Day has been read
2 Day has been read
3 Day has been read
4 Day has been read
5 Day has been read
6 Day has been read
7 Day has been read
8 Day has been read
6 Participant has been read
1 Day has been read
2 Day has been read
3 Day has been read
4 Day has been read
5 Day has been read
6 Day has been read
7 Day has been read
8 Day has been read
9 Day has been read
10 Day has been read
11 Day has been read
12 Day has been read
13 Day has been read
14 Day has been read
15 Day has been read
16 Day has been read
17 Day has been read
18 Day has been read
19 Day has been read
20 Day has been read
21 Day has been read
22 Day has been read
8 Participant has been read
1 Day has been read
2 Day has been read
3 Day has been read
4 Day has been read
5 Day has been read
6 Day has been read
7 Day has been read
8 Day has been read
9 Day has been read
10 Day has been read
11 Day has been read
12 Day has been read
13 Day has been read
14 Day has been read
15 Day has been read
16 Day has been read
17 Day has been read
18 Day has been read
19 Day has been read
20 Day has been read
21 Day has been read
22 Day has been read
9 Participant has been read
1 Day has been read
2 Day has been read
3 Day has been read
4 Day has been read
5 Day has been read
6 Day has been read
7 Day has been read
8 Day has been read
9 Day has been read
10 Day has been read
11 Day has been read
12 Day has been read
13 Day has been read
14 Day has been read
15 Day has been read
16 Day has been read
17 Day has been read
18 Day has been read
19 Day has been read
20 Day has been read
10 Participant has been read
1 Day has been read
2 Day has been read
3 Day has been read
4 Day has been read
5 Day has been read
6 Day has been read
7 Day has been read
8 Day has been read
9 Day has been read
10 Day has been read
11 Day has been read
12 Day has been read
13 Day has been read
14 Day has been read
15 Day has been read

In [72]:
patients.insert(3,'TD')
for t in patients['Time Stamp']:
    patients['TD'].loc[t] = patients['Time Stamp'].loc[t+1] - patients['Time Stamp'].loc[t]

TypeError: list indices must be integers or slices, not str

In [82]:
patients[0]
#p['Band Contact'] == 'WORN'
#print('Average wear time', (patient.worn == 1).mean())
#patient['worn'].plot()

      PID  DAY       Time Stamp Band Contact  Skin Temperature(°C)
0       1    1  14:00:35.683000     NOT_WORN                 21.62
1       1    1  14:22:11.274000         WORN                 29.01
2       1    1  14:22:42.686000         WORN                 29.11
3       1    1  14:23:13.832000         WORN                 29.20
4       1    1  14:24:23.947000         WORN                 29.06
5       1    1  14:24:23.986000         WORN                 29.06
6       1    1  14:24:46.695000         WORN                 28.86
7       1    1  14:25:17.694000         WORN                 28.84
8       1    1  14:25:48.695000         WORN                 28.90
9       1    1  14:26:19.686000         WORN                 29.03
10      1    1  14:26:50.695000         WORN                 29.15
11      1    1  14:27:22.185000         WORN                 29.25
12      1    1  14:27:52.820000         WORN                 29.34
13      1    1  14:28:24.184000         WORN                 29.47
14      1    1  14:28:55.184000         WORN                 29.51
15      1    1  14:29:26.197000         WORN                 29.55
16      1    1  14:29:57.186000         WORN                 29.58
17      1    1  14:30:17.193000     NOT_WORN                 29.58
18      1    1  14:30:22.694000         WORN                 29.58
19      1    1  14:30:28.686000         WORN                 30.43
20      1    1  14:30:59.682000         WORN                 30.77
21      1    1  14:31:30.695000         WORN                 30.92
22      1    1  14:32:01.686000         WORN                 30.97
23      1    1  14:32:32.684000         WORN                 31.05
24      1    1  14:33:04.195000         WORN                 31.12
25      1    1  14:33:35.194000         WORN                 31.14
26      1    1  14:34:06.195000         WORN                 31.24
27      1    1  14:34:37.342000         WORN                 31.24
28      1    1  14:35:08.189000         WORN                 31.31
29      1    1  14:35:39.838000         WORN                 31.40
...   ...  ...              ...          ...                   ...
1011    1    1  23:44:29.274000         WORN                 34.66
1012    1    1  23:45:00.279000         WORN                 34.66
1013    1    1  23:45:31.280000         WORN                 34.69
1014    1    1  23:46:02.278000         WORN                 34.72
1015    1    1  23:46:33.273000         WORN                 34.77
1016    1    1  23:47:04.213000         WORN                 34.79
1017    1    1  23:47:35.130000         WORN                 34.78
1018    1    1  23:48:06.630000         WORN                 34.79
1019    1    1  23:48:37.743000         WORN                 34.78
1020    1    1  23:49:08.747000         WORN                 34.78
1021    1    1  23:49:39.747000         WORN                 34.78
1022    1    1  23:50:10.752000         WORN                 34.79
1023    1    1  23:50:42.275000         WORN                 34.80
1024    1    1  23:51:13.277000         WORN                 34.79
1025    1    1  23:51:44.212000         WORN                 34.78
1026    1    1  23:52:15.210000         WORN                 34.78
1027    1    1  23:52:46.215000         WORN                 34.79
1028    1    1  23:53:17.780000         WORN                 34.78
1029    1    1  23:53:48.625000         WORN                 34.80
1030    1    1  23:54:19.759000         WORN                 34.80
1031    1    1  23:54:50.742000         WORN                 34.80
1032    1    1  23:55:21.750000         WORN                 34.80
1033    1    1  23:55:52.747000         WORN                 34.82
1034    1    1  23:56:23.772000         WORN                 34.84
1035    1    1  23:56:54.777000         WORN                 34.87
1036    1    1  23:57:25.713000         WORN                 34.84
1037    1    1  23:57:56.780000         WORN                 34.85
1038    1    1  23:58:28.208000         WORN                 34.85
1039    1    1  23:58:59.280000         WORN                 34.85
1040    1    1  23:59:30.279000         WORN                 34.85

[1041 rows x 5 columns]

9

16

MS_Band_Raw/                  cag2018_callforabstracts.pdf
Untitled.ipynb

3

NameError: name 'plist' is not defined

MS_Band_Raw/                  cag2018_callforabstracts.pdf
MS_band_analysis.ipynb

      PID Band Contact  Skin Temperature(°C)          Time Stamp
0       6     NOT_WORN                 28.12 2018-04-10 00:00:07
1       6     NOT_WORN                 27.97 2018-04-10 00:00:38
2       6     NOT_WORN                 27.82 2018-04-10 00:01:09
3       6     NOT_WORN                 27.70 2018-04-10 00:01:40
4       6     NOT_WORN                 27.55 2018-04-10 00:02:11
5       6     NOT_WORN                 27.40 2018-04-10 00:02:42
6       6     NOT_WORN                 27.22 2018-04-10 00:03:13
7       6     NOT_WORN                 27.10 2018-04-10 00:03:44
8       6     NOT_WORN                 26.94 2018-04-10 00:04:15
9       6     NOT_WORN                 26.95 2018-04-10 00:04:46
10      6     NOT_WORN                 26.77 2018-04-10 00:05:18
11      6     NOT_WORN                 26.60 2018-04-10 00:05:49
12      6     NOT_WORN                 26.44 2018-04-10 00:06:20
13      6     NOT_WORN                 26.35 2018-04-10 00:06:51
14      6     NOT_WORN                 26.19 2018-04-10 00:07:22
15      6     NOT_WORN                 26.08 2018-04-10 00:07:53
16      6     NOT_WORN                 25.94 2018-04-10 00:08:24
17      6     NOT_WORN                 25.80 2018-04-10 00:08:55
18      6     NOT_WORN                 25.70 2018-04-10 00:09:26
19      6     NOT_WORN                 25.59 2018-04-10 00:09:57
20      6     NOT_WORN                 25.48 2018-04-10 00:10:29
21      6     NOT_WORN                 25.37 2018-04-10 00:11:00
22      6     NOT_WORN                 25.29 2018-04-10 00:11:31
23      6     NOT_WORN                 25.19 2018-04-10 00:12:02
24      6     NOT_WORN                 25.12 2018-04-10 00:12:33
25      6     NOT_WORN                 25.05 2018-04-10 00:13:04
26      6     NOT_WORN                 24.98 2018-04-10 00:13:35
27      6     NOT_WORN                 24.93 2018-04-10 00:14:06
28      6     NOT_WORN                 24.86 2018-04-10 00:14:37
29      6     NOT_WORN                 24.81 2018-04-10 00:15:08
...   ...          ...                   ...                 ...
1036    6         WORN                 30.96 2018-04-10 00:44:38
1037    6         WORN                 31.05 2018-04-10 00:45:09
1038    6         WORN                 30.95 2018-04-10 00:45:40
1039    6         WORN                 31.07 2018-04-10 00:46:11
1040    6         WORN                 31.07 2018-04-10 00:46:42
1041    6         WORN                 31.06 2018-04-10 00:47:13
1042    6         WORN                 31.03 2018-04-10 00:47:44
1043    6         WORN                 30.94 2018-04-10 00:48:15
1044    6         WORN                 30.90 2018-04-10 00:48:46
1045    6         WORN                 30.90 2018-04-10 00:49:17
1046    6         WORN                 30.95 2018-04-10 00:49:48
1047    6         WORN                 30.92 2018-04-10 00:50:20
1048    6         WORN                 31.01 2018-04-10 00:50:51
1049    6         WORN                 31.14 2018-04-10 00:51:21
1050    6         WORN                 31.14 2018-04-10 00:51:52
1051    6         WORN                 31.24 2018-04-10 00:52:24
1052    6         WORN                 31.37 2018-04-10 00:52:55
1053    6         WORN                 31.55 2018-04-10 00:53:26
1054    6         WORN                 31.55 2018-04-10 00:53:57
1055    6         WORN                 31.51 2018-04-10 00:54:28
1056    6         WORN                 31.53 2018-04-10 00:54:59
1057    6         WORN                 31.59 2018-04-10 00:55:30
1058    6         WORN                 31.68 2018-04-10 00:56:01
1059    6         WORN                 31.80 2018-04-10 00:56:32
1060    6         WORN                 31.92 2018-04-10 00:57:03
1061    6         WORN                 32.03 2018-04-10 00:57:35
1062    6         WORN                 32.15 2018-04-10 00:58:06
1063    6         WORN                 32.31 2018-04-10 00:58:37
1064    6         WORN                 32.18 2018-04-10 00:59:08
1065    6         WORN                 32.09 2018-04-10 00:59:39

[1066 rows x 4 columns]

Timestamp('1970-01-01 00:00:00')

15:30:45

0       0.0
1       0.0
2       0.0
3       0.0
4       0.0
5       0.0
6       0.0
7       0.0
8       0.0
9       0.0
10      0.0
11      0.0
12      0.0
13      0.0
14      0.0
15      0.0
16      0.0
17      0.0
18      0.0
19      0.0
20      0.0
21      0.0
22      0.0
23      0.0
24      0.0
25      0.0
26      0.0
27      0.0
28      0.0
29      0.0
       ...
1036    0.0
1037    0.0
1038    0.0
1039    0.0
1040    0.0
1041    0.0
1042    0.0
1043    0.0
1044    0.0
1045    0.0
1046    0.0
1047    0.0
1048    0.0
1049    0.0
1050    0.0
1051    0.0
1052    0.0
1053    0.0
1054    0.0
1055    0.0
1056    0.0
1057    0.0
1058    0.0
1059    0.0
1060    0.0
1061    0.0
1062    0.0
1063    0.0
1064    0.0
1065    0.0
Name: 24, Length: 1066, dtype: float64

zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero
zero